version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always 
    container_name: local_apps
    command: php -S 0.0.0.0:8080
    ports:
      - 80:8080
    volumes:
       - .:/app